In [1]:
!pip install xlrd

     |████████████████████████████████| 112kB 30.2MB/s eta 0:00:01


## Import Dataset

In [2]:
import pandas as pd
df=pd.read_excel('Titanic_Train.xlsx')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

## Missing Values

In [3]:
dfmean=df['Age'].mean()
dfmean

29.69911764705882

In [22]:
import numpy as np

In [5]:
df["Age"].fillna(dfmean,inplace=True)

In [6]:
df["Embarked"].fillna(df["Embarked"].mode()[0],inplace=True)

## Drop the irrelevant columns

In [7]:
df.drop(['Cabin'],axis=1,inplace=True)

In [8]:
df.drop(['Name'],axis=1, inplace=True)

In [116]:
df.head()

PassengerId  Survived  Pclass     Sex   Age  SibSp  Parch  \
0            1         0       3    male  22.0      1      0   
1            2         1       1  female  38.0      1      0   
2            3         1       3  female  26.0      0      0   
3            4         1       1  female  35.0      1      0   
4            5         0       3    male  35.0      0      0   

             Ticket     Fare Embarked  
0         A/5 21171   7.2500        S  
1          PC 17599  71.2833        C  
2  STON/O2. 3101282   7.9250        S  
3            113803  53.1000        S  
4            373450   8.0500        S

## Convert Categorical values

In [9]:
df['Sex'].replace('male',1,inplace=True)

In [10]:
df['Sex'].replace('female',0,inplace=True)

In [11]:
df['Embarked'].replace(to_replace=['S','C','Q'],value=[0,1,2],inplace=True)

## Feature Selection

In [14]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [19]:
BestFeatures=SelectKBest(score_func=chi2,k=8)
fit=BestFeatures.fit(X,Y)

In [23]:
dfcols=pd.DataFrame(df.columns)

In [24]:
dfscores=pd.DataFrame(fit.scores_)

In [25]:
Features=pd.concat([dfcols,dfscores],axis=1)

In [26]:
Features

0            0
0  PassengerId     3.312934
1     Survived    30.873699
2       Pclass    92.702447
3          Sex    24.687926
4          Age     2.581865
5        SibSp    10.097499
6        Parch  4518.319091
7       Ticket    11.353117
8         Fare          NaN
9     Embarked          NaN

In [27]:
X=df[['PassengerId','Pclass','Sex','Age','SibSp','Parch']].values

In [124]:
X

array([[  1.    ,   3.    ,   1.    , ...,   0.    ,   7.25  ,   0.    ],
       [  2.    ,   1.    ,   0.    , ...,   0.    ,  71.2833,   1.    ],
       [  3.    ,   3.    ,   0.    , ...,   0.    ,   7.925 ,   0.    ],
       ...,
       [889.    ,   3.    ,   0.    , ...,   2.    ,  23.45  ,   0.    ],
       [890.    ,   1.    ,   1.    , ...,   0.    ,  30.    ,   1.    ],
       [891.    ,   3.    ,   1.    , ...,   0.    ,   7.75  ,   2.    ]])

In [28]:
Y=df['Survived'].values

## Data Preprocessing

In [29]:
from sklearn import preprocessing
X=preprocessing.StandardScaler().fit(X).transform(X.astype(float))

## Train Test Split

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=10)

## ML Algorithms

### Decision Tree

In [17]:
from sklearn.tree import DecisionTreeClassifier

In [18]:
dectree=DecisionTreeClassifier(criterion='gini',max_depth=4)

In [19]:
dectree.fit(X_train,Y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=4,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [20]:
pred=dectree.predict(X_test)

In [132]:
pred

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1])

### Accuracy

In [21]:
from sklearn import metrics

In [22]:
metrics.accuracy_score(Y_test,pred)

0.8171641791044776

### Hyper parameter tuning

In [55]:
from sklearn.model_selection import GridSearchCV
params={'criterion':['entropy','gini'],'max_depth':[1,2,3,4,5,6,7,8,9,10]}

In [141]:
gs=GridSearchCV(estimator=dectree,param_grid=params,cv=3)

In [142]:
gs.fit(X_train,Y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=2,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'criterion': ['entropy', 'gini'], 'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [143]:
gs.best_params_

{'criterion': 'gini', 'max_depth': 4}

In [144]:
gs.best_score_

0.8073836276083467

In [152]:
from sklearn.model_selection import cross_val_score

In [153]:
dec=DecisionTreeClassifier(criterion='gini',max_depth=4)

In [154]:
print(cross_val_score(dec,X,Y,cv=10,scoring='accuracy').mean())

0.7902581999773011


### SVM

In [23]:
from sklearn import svm
clf=svm.SVC(kernel='rbf')
clf.fit(X_train,Y_train)

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [24]:
pred2=clf.predict(X_test)

### Accuracy

In [25]:
metrics.accuracy_score(Y_test,pred2)

0.8208955223880597

### Hyper parameter tuning

In [30]:
from sklearn.model_selection import GridSearchCV
params2={'kernel':['rbf','sigmoid','linear']}

In [31]:
gs2=GridSearchCV(estimator=clf,param_grid=params2,cv=3)

In [32]:
gs2.fit(X_train,Y_train)

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
/home/jupyterlab/co

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='rbf', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'kernel': ['rbf', 'sigmoid', 'linear']},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [33]:
gs2.best_params_

{'kernel': 'rbf'}

In [34]:
gs2.best_score_

0.8154093097913323

### Logistic Regression

In [44]:
from sklearn.linear_model import LogisticRegression
LR=LogisticRegression(C=0.02,solver='sag')
LR.fit(X_train,Y_train)


LogisticRegression(C=0.02, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='sag',
          tol=0.0001, verbose=0, warm_start=False)

In [45]:
pred3=LR.predict(X_test)

### Accuracy

In [46]:
metrics.accuracy_score(Y_test,pred3)

0.8059701492537313

### Hyper parameter tuning

In [39]:
params3={'solver':['liblinear','sag','saga','newton-cg','lbfgs'],'C':[0.01,0.02,0.03,0.001]}

In [40]:
gs3=GridSearchCV(estimator=LR,param_grid=params3,cv=3)

In [41]:
gs3.fit(X_train,Y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='liblinear',
          tol=0.0001, verbose=0, warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'solver': ['liblinear', 'sag', 'saga', 'newton-cg', 'lbfgs'], 'C': [0.01, 0.02, 0.03, 0.001]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [42]:
gs3.best_params_

{'C': 0.02, 'solver': 'sag'}

In [47]:
gs3.best_score_

0.8041733547351525

### K- Nearest Neighbor

In [33]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics

In [34]:
ks=16
mean_acc=np.zeros(ks-1)
for i in range(1,ks):
    neigh=KNeighborsClassifier(n_neighbors=i)
    neigh.fit(X_train,Y_train)
    pred_=neigh.predict(X_test)
    mean_acc[i-1]=metrics.accuracy_score(Y_test,pred_)
mean_acc

array([0.74626866, 0.77985075, 0.80223881, 0.81716418, 0.82462687,
       0.82089552, 0.82089552, 0.82462687, 0.83208955, 0.84328358,
       0.83208955, 0.84701493, 0.83955224, 0.82835821, 0.82835821])

In [60]:
k=8
neigh=KNeighborsClassifier(n_neighbors=k)
neigh.fit(X_train,Y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=8, p=2,
           weights='uniform')

In [61]:
pred4=neigh.predict(X_test)

In [38]:
pred4

array([0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0])

### Accuracy

In [62]:
metrics.accuracy_score(Y_test,pred4)

0.8246268656716418

### Hyper parameter tuning

In [56]:
params4={'n_neighbors':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]}

In [57]:
gs4=GridSearchCV(estimator=neigh,param_grid=params4,cv=3)

In [58]:
gs4.fit(X_train,Y_train)

GridSearchCV(cv=3, error_score='raise-deprecating',
       estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=12, p=2,
           weights='uniform'),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=0)

In [59]:
gs4.best_params_

{'n_neighbors': 8}

## Test dataset

In [39]:
df2=pd.read_excel('Titanic_Test.xlsx')
df2.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [40]:
dfmean2=df2['Age'].mean()
dfmean2

30.272590361445783

In [41]:
df2["Age"].fillna(dfmean2,inplace=True)

In [66]:
df2.head(10)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
5          897       3                    Svensson, Mr. Johan Cervin    male   
6          898       3                          Connolly, Miss. Kate  female   
7          899       2                  Caldwell, Mr. Albert Francis    male   
8          900       3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female   
9          901       3                       Davies, Mr. John Samuel    male   

    Age  SibSp  Parch     Ticket     Fare Cabin Embarked  
0  34.5      0      0     330911   7.8292   NaN        Q  
1  47.0      1      0     363272   7.0000   NaN        S  
2  62.0      0      0     240276   9.6875   NaN        Q  
3  27.0      0      0     315154   8.6625   NaN        S  
4  22.0      1      1    3101298  12.2875   NaN        S  
5  14.0      0      0       7538   9.2250   NaN        S  
6  30.0      0      0     330972   7.6292   NaN        Q  
7  26.0      1      1     248738  29.0000   NaN        S  
8  18.0      0      0       2657   7.2292   NaN        C  
9  21.0      2      0  A/4 48871  24.1500   NaN        S

In [42]:
df2.drop(['Cabin'],axis=1,inplace=True)

In [43]:
df2.drop(['Name'],axis=1,inplace=True)

In [69]:
df2.head()

PassengerId  Pclass     Sex   Age  SibSp  Parch   Ticket     Fare Embarked
0          892       3    male  34.5      0      0   330911   7.8292        Q
1          893       3  female  47.0      1      0   363272   7.0000        S
2          894       2    male  62.0      0      0   240276   9.6875        Q
3          895       3    male  27.0      0      0   315154   8.6625        S
4          896       3  female  22.0      1      1  3101298  12.2875        S

In [44]:
df2['Embarked'].replace(to_replace=['S','C','Q'],value=[0,1,2],inplace=True)

In [45]:
df2['Sex'].replace(to_replace=['female','male'],value=[0,1],inplace=True)

In [72]:
df2.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch   Ticket     Fare  Embarked
0          892       3    1  34.5      0      0   330911   7.8292         2
1          893       3    0  47.0      1      0   363272   7.0000         0
2          894       2    1  62.0      0      0   240276   9.6875         2
3          895       3    1  27.0      0      0   315154   8.6625         0
4          896       3    0  22.0      1      1  3101298  12.2875         0

In [46]:
df2.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           1
Embarked       0
dtype: int64

In [47]:
df2["Fare"].fillna(df2["Fare"].mean(),inplace=True)

In [52]:
df2.isnull().sum()

PassengerId    0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [49]:
X2=df2[['PassengerId','Pclass','Sex','Age','SibSp','Parch']].values

### Applying the algorithm to test dataset

In [63]:
result=neigh.predict(X2)

In [64]:
result

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [116]:
prediction=pd.DataFrame(result)

In [117]:
prediction.head(10)

0
0  0
1  1
2  0
3  0
4  0
5  0
6  0
7  0
8  0
9  0

In [118]:
prediction.to_csv(r'NewSubmission.csv', index=False)